### PR TITLE
Remove (provide 'test-helper)

### LINKED ISSUE #4: Please add a prefix to test-helper.el to avoid conflicts with 68 other packages
There exist at least 69 packages that contain a file named `test-helper.el` that also provides the feature `test-helper`.

This leads to issues for users who have at least two of these packages installed.  It is unlikely that such a user would be able to run the tests of all of those packages.  If the primary test file of one of those packages does `(require 'test-helper)`, then it is undefined which of the various `test-helper.el` files gets loaded.  Which it is, depends on the order of the `load-path`.

To avoid this conflicts, you should rename your `test-helper.el` to `<your-package>-test-helper.el` and adjust the feature and symbol prefixes accordingly.

Also don't forget to update the `require` form in your primary test file and/or update references to the library/feature elsewhere.  Also, if your primary test file is named something like `test.el`, then please consider renaming that too (same for any other utility elisp files your repositoroy may contain).

Thanks!

PS: This issue is a bit generic because I had to open 69 issues.

### PR DESCRIPTION
**Pull request by zonuexe**
@tarsius fixes #4

### CODE REVIEW

**Comment by tarsius** [comment]
Were you waiting for my feedback? If so; yes, that's the change I was after.

**Comment by zonuexe** [comment]
@Wilfred 
Could you see this PR?

@tarsius *(I'm not maintainer of this project)*

**Comment by tarsius** [comment]
Ah! ;-)

**Review by Wilfred — APPROVED** [review]

**Comment by tarsius** [comment]
Thanks to both of you!

**Pull request merged**
